MvcProjeOrnek/Controllers/SecurityController.cs
using MvcProjeOrnek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
namespace MvcProjeOrnek.Controllers
{
    public class SecurityController : Controller
    {
        Model1Container db = new Model1Container();
        // GET: Security
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Kullanicilar kullanici)
        {

            var users = db.KullanicilarSet.FirstOrDefault(i => i.kullaniciAdi == kullanici.kullaniciAdi && i.sifre == kullanici.sifre);
            if (users != null)
            {

                FormsAuthentication.SetAuthCookie(users.kullaniciAdi, true);
                return RedirectToAction("Index","Admin");

            }

            else
            {
                ViewBag.Mesaj = "Kullanıcı Adı veya parola yanlış";
                return View();
            }



        }
        public ActionResult Logout()
        {

            return RedirectToAction("Login");
        }


    }
}

MvcProjeOrnek/Views/Security/Login.cshtml
@model  MvcProjeOrnek.Models.Kullanicilar
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            background-image: url("../plaj.png");
            background-repeat: no-repeat;
            background-position: center center;
            background-attachment: fixed;
            background-size: cover;
          
        }


        .container {
            background-image: url("../plaj1.png");
            background-repeat: no-repeat;
            background-position: left;
            border-radius:50px;
            width:450px;
            
            
        }
    </style>
</head>
<body>

    <div class="container" style="margin-top: 150px; margin-left:500px; ">
        <b style=" margin-left: 40px; margin-top: 10px; color: yellow; font-size: 25px; font-family: 'Times New Roman', Times, serif, 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">  Kullanıcı Giriş Sayfası</b>
        @using (Html.BeginForm("Login", "Security", FormMethod.Post))
        {
            <div style="margin-top:10px;  margin-left:20px; ">
                @Html.LabelFor(i => i.kullaniciAdi, new { Style = "color:yellow; margin-left: 20px;  font-size:30px;" })
                <div style="margin-top: 5px; width: 300px; margin-left: 20px;">
                    @Html.TextBoxFor(i => i.kullaniciAdi, new { @class = "form-control", placeholder = "Lütfen kullanıcı adını giriniz..." })
                </div>
            </div>

            <div style="margin-top: 20px; width: 300px; margin-left: 20px;">
                @Html.LabelFor(i => i.sifre, new { Style = "color:yellow; font-size:30px; margin-left: 20px;" })
                <div style="margin-top: 5px; margin-left: 25px; width:300px;">
                    @Html.PasswordFor(i => i.sifre, new { @class = "form-control", placeholder = "Lütfen şifrenizi giriniz..." })
                </div>
            </div>

            <button type="submit" class="btn btn-warning" style="margin-top: 20px; margin-bottom: 15px; width: 300px; margin-left: 45px; color:white; font-size:16px;">Giriş Yap</button>
        }


    </div>
</body>
</html>